"""updated information on user document

Revision ID: 96bb457a9a36
Revises: 
Create Date: 2025-01-19 07:46:17.304515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96bb457a9a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=80), nullable=False),
    sa.Column('l_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('GENERAL_ADMIN', 'MANAGEMENT', 'TECH_SUPPORT', 'ON_SITE_TECHNICIAN', name='roleenum'), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('f_name'),
    sa.UniqueConstraint('l_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
